Feat search
code100x/daily-code pull request #440
Opened 2024-05-19 20:03 UTC by ShubhamMewara

### PR Fixes: #175 
reopen #294 
update: Removed Algolia ( keyword search )
Added vector search using: 
- google gemini for embeddings
- qdrant for vector  db [Qdrant ](https://qdrant.tech/)

https://github.com/code100x/daily-code/assets/136337515/ab4fe300-85f3-4cb2-838f-760dcf3d6f9c

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

2024-06-18 21:36 UTC, siinghd requested changes
for now this, 
Honestly i dont know if we need this much or this advanced search. Current search is not bad tho

2024-06-18 21:36 UTC, siinghd commented on apps/web/components/ContentSearch.tsx
> +    debounce(async (searchQuery: string) => {
can't we just use useDeferredValue ? creating own debounce?

2024-06-18 21:36 UTC, siinghd commented on apps/web/components/ContentSearch.tsx
> +            window.open(`/tracks/${selectedTrack?.payload.trackId}/${selectedTrack?.payload.problemId}`, "_blank");
can we use default nextjs rounting for this instead of window.open?

2024-06-18 21:36 UTC, siinghd commented on apps/web/components/ContentSearch.tsx
> +function debounce<T extends (...args: any[]) => any>(func: T, delay: number): (...args: Parameters<T>) => void {
duplicate, use [useDeferredValue](https://react.dev/reference/react/useDeferredValue)](https://react.dev/reference/react/useDeferredValue)

2024-06-18 21:43 UTC, siinghd commented
@hkirat do we need this? i am not convinced about this

2024-06-19 08:46 UTC, ShubhamMewara commented
> @hkirat do we need this? i am not convinced about this

@hkirat he made the issue #175

2024-06-24 23:06 UTC, hkirat commented
/bounty $120

2024-06-24 23:07 UTC, hkirat commented
@siinghd

2024-06-24 23:07 UTC, hkirat commented
Updated the bounty to $100

2024-06-24 23:08 UTC, siinghd commented
On it

2024-06-25 00:37 UTC, siinghd commented
@hkirat you will have to update the .env... tested it in local working really good. code looks also good.

merging it, just update the .env and the db stuff

2024-06-25 00:37 UTC, merged