Added Home button while viewing a specific track
code100x/daily-code pull request #492
Opened 2024-07-11 18:32 UTC by tillu002

### PR Fixes:
- 1 Added home button to the BlogAppBar so that it will be easy to come out of the tracks easily
![Screenshot 2024-07-11 235410](https://github.com/code100x/daily-code/assets/121672097/25233d5d-7c67-40b0-a26c-9155d00221d6)

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

2024-07-11 18:48 UTC, tillu002 commented
[https://github.com/code100x/daily-code/pull/492#issue-2403841965](url)

2024-07-17 15:23 UTC, siinghd requested changes

2024-07-17 15:23 UTC, siinghd commented on apps/web/components/BlogAppbar.tsx
> +          <button onClick={handleGoHome}>
why use button here?, can we use link?

2024-08-07 03:09 UTC, devsargam commented
closing due to inactivity

2024-08-07 03:09 UTC, closed without merging