Added the cache for the getproblem function
code100x/daily-code pull request #495
Opened 2024-07-12 06:09 UTC by Ameerjafar

Resolves #[490] 

### Checklist before requesting a review

- [ yes ] I assure there is no similar/duplicate pull request regarding same issue

2024-07-17 15:22 UTC, siinghd requested changes

2024-07-17 15:22 UTC, siinghd commented on apps/web/components/utils.tsx
> +    console.log("successfully added");
remove console.log

2024-07-17 15:22 UTC, siinghd commented on apps/web/components/utils.tsx
> +    console.log("get successfully");
remove console.log

2024-07-17 15:22 UTC, siinghd commented on apps/web/components/utils.tsx
> +    console.log(tracks);
remove console.log

2024-07-17 15:22 UTC, siinghd commented on apps/web/components/utils.tsx
> +    console.log("hello set successfully");
remove console.log

2024-07-18 14:28 UTC, Ameerjafar commented on apps/web/components/utils.tsx
> +    console.log("successfully added");
done sir

2024-07-18 14:28 UTC, Ameerjafar commented on apps/web/components/utils.tsx
> +    console.log(tracks);
done sir.

2024-07-19 04:49 UTC, merged

2024-07-19 07:11 UTC, Ameerjafar commented
Any bounties😁😁😁? @hkirat