feat-604: Added input to change cohort in Admin Panel
code100x/daily-code pull request #605
Opened 2024-08-30 19:39 UTC by ItsFlash10

### PR Fixes:
- Admin would be able to change the cohort for any uploaded track.

Resolves #604 

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

2024-08-30 19:47 UTC, ItsFlash10 commented
PS: UI can be improved as well but I've catered the functionality atm as it's important as highlighted a couple of days ago for the filters.

2024-09-01 05:49 UTC, devsargam commented on apps/web/app/admin/layout.tsx
Just a suggestion from my side. Try to turn off your preferred formatting tool and try to minimise the diff.
![image](https://github.com/user-attachments/assets/ee945b87-595b-44df-9a71-be890ce0e028)

2024-09-01 05:50 UTC, devsargam approved these changes

2024-09-01 05:50 UTC, devsargam commented
Testing locally

2024-09-01 06:12 UTC, ItsFlash10 commented on apps/web/app/admin/layout.tsx
> Just a suggestion from my side. Try to turn off your preferred formatting tool and try to minimise the diff. ![image](https://private-user-images.githubusercontent.com/76874341/363461753-ee945b87-595b-44df-9a71-be890ce0e028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzEyODQsIm5iZiI6MTcyNTE3MDk4NCwicGF0aCI6Ii83Njg3NDM0MS8zNjM0NjE3NTMtZWU5NDViODctNTk1Yi00NGRmLTlhNzEtYmU4OTBjZTBlMDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA2MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzIwMmNmNDQ2YWNlNjdhZDA3NmUyNGYzMWY1MGZjMDA3NjY5ZGNlYWUwNGVkYzY5Yzg5YTE0NWI3NWVhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXTjerL4qdUeEu31bXEmWPOAvdRuxdGq2B-s_i0wcAQ)

Will do that, it's there actually as I added `prettier-tailwind-plugin` in the last PR as it was missing in this project and I think I added a log or something there and later removed it but the classes got sorted coz of the plugin.

2024-09-01 06:25 UTC, devsargam commented on apps/web/app/admin/layout.tsx
Cool, but usually formatting change will be a separate pr in itself and happens when the repo's pr count is almost 0. Good thing to keep in mind tho.

2024-09-01 06:33 UTC, ItsFlash10 commented on apps/web/app/admin/layout.tsx
Yes ser

2024-09-01 16:20 UTC, devsargam commented
This updates the backend but can we get the filter functionality working too?

2024-09-01 16:20 UTC, devsargam requested changes
Make the filter option working as well

2024-09-01 16:56 UTC, ItsFlash10 commented
> Make the filter option working as well

Done

2024-09-08 21:24 UTC, devsargam approved these changes

2024-09-08 21:30 UTC, devsargam commented
Testing locally tomorrow

2024-09-09 16:26 UTC, devsargam commented
works perfectly

2024-09-09 16:26 UTC, merged

2024-09-09 16:35 UTC, devsargam commented
Thank u @ItsFlash10. You will receive the bounty later